### PR TITLE
Simplified Chinese translation

### PR DESCRIPTION
**Pull request by GlitchedReme**
My friends and I have finished the Chinese translation, please add this into the mod ::)

If you want to add credits, just write "星际拓荒讨论群群友".

### CODE REVIEW

**Comment by hearth1an** [comment]
Thanks! Sure, I'll add you to credits and ingame credits as well!

**Comment by hearth1an** [comment]
@REME-easy seems like ingame credits don't support any other language, just english

photo_2022-09-07_16-38-00

How I can give you a credit there?

**Comment by GlitchedReme** [comment]
Oh, "Chinese Outer Wilds lovers" is also OK, because many people have contributed.
Thanks for your mod too!!

**Comment by hearth1an** [comment]
image
done! will make an update soon. Thx for contributing guys, hope you liked this mod!

**Pull request merged**
